on: [push, pull_request, deployment]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          event: ${{ toJson(github.event) }}
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.AHO_SLACK_TOKEN }}
          channel: proba
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

